apiVersion: v1
kind: Pod
metadata:
  name: nfstest
  labels:
    app: nfstest
spec:
  containers:
  - name: nfstest-container
    image: gourao/nfstest
    imagePullPolicy: Always
    securityContext:
      privileged: true	
    command: ["/usr/local/bin/nfusr"]
    args: ["-f", "nfs://NETAPP_IP/trident_pvc_faba8030_57f4_4b62_9976_593633f17327", "/data"]
  restartPolicy: OnFailure
