apiVersion: v1
kind: Pod
metadata:
  name: nfstest
  labels:
    app: nfstest
spec:
  containers:
  - name: nfstest-container
    image: gourao/nfstest
    imagePullPolicy: Always
    securityContext:
      privileged: true	
    command: ["/usr/local/bin/nfusr"]
    args: ["-f", "nfs://172.31.53.180/PVC", "/data"]
  restartPolicy: OnFailure
